<?php

/**
 * Title: BuildPros - Banner featuring image, text, and button
 * Slug: buildpros/banner-1
 * Categories: call-to-action
 * Viewport Width: 1280
 */

$img_url = esc_url(get_theme_file_uri('assets/images/demo/demo-7.jpg')); /* <?php echo esc_url( $img_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"custom-color","bg_color":"rgba(8,8,8,0.53)","bg_image":"<?php echo esc_url( $img_url ); ?>","bg_image_id":5529,"bg_image_xy":{"x":0.69,"y":0.29},"mb_lg":"","pt":"8","pb":"7","pt_lg":"10","pb_lg":"9","position":"position-relative","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-color'  bg_color='rgba(8,8,8,0.53)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image='<?php echo esc_url( $img_url ); ?>'  bg_image_id='5529'  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='8'  pr=''  pb='7'  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='10'  pr_lg=''  pb_lg='9'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-8 pb-7 pt-lg-10 pb-lg-9 bg-custom-color bg-image-fixed container-fluid position-relative" style="background-color:rgba(8,8,8,0.53);background-image:url(<?php echo esc_url( $img_url ); ?>);background-blend-mode:overlay;background-size:cover;background-position:69% 28.999999999999996%"><!-- wp:blockstrap/blockstrap-widget-shape-divider {"sd":"tilt","sd_position":"top","sd_color":"white","sd_width":"146","sd_height":"76","styleid":"block-n21z1f5m8j","sd_shortcode":"[bs_shape_divider sd='tilt'  sd_position='top'  sd_color='white'  sd_custom_color='#0073aa'  sd_width='146'  sd_height='76'  sd_flip='false'  sd_invert='false'  sd_btf='false'  styleid='block-n21z1f5m8j' ]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-shape-divider block-n21z1f5m8j blockstrap-shape blockstrap-shape-top position-absolute"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 100" preserveAspectRatio="none">	<path class="bg-white blockstrap-shape-fill" d="M0,6V0h1000v100L0,6z"/></svg></div><style>.block-n21z1f5m8j { pointer-events: none;background-repeat: no-repeat;left: -1px;right: -1px;top: -1px;line-height: 0;overflow: hidden;margin: 0 1px;}.block-n21z1f5m8j svg{ height: 76px;width: calc(146% + 1.3px);left: 50%;position: relative;display: block;-webkit-transform: translateX(-50%); -ms-transform: translateX(-50%); transform: translateX(-50%);}.block-n21z1f5m8j svg path{ }</style>
<!-- /wp:blockstrap/blockstrap-widget-shape-divider -->

<!-- wp:blockstrap/blockstrap-widget-container {"mb_lg":"","content":"\u003cdiv class=\u0022bs-counter-number-wrapper text-dark text-start fw-bold  h1 \u0022  \u003e\u003cspan class=\u0022bs-counter-number\u0022 data-auicounter data-auistart=\u00220\u0022 data-auiend=\u002256\u0022 data-auiduration=\u00222000\u0022 data-auisep=\u0022\u0022\u003e56\u003c/span\u003e\u003cspan class=\u0022bs-counter-suffix\u0022\u003eK+\u003c/span\u003e\u003c/div\u003e\u003cdiv class=\u0022bs-counter-title text-start fs-5 \u0022 \u003eMonthly Users\u003c/div\u003e","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container bg-image-fixed container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols":"1","mb_lg":"","flex_align_items_lg":"align-items-lg-center","sd_shortcode":"[bs_container container='row'  h100=''  row_cols='1'  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container row-cols-1 bg-image-fixed row align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col_md":"12","col_lg":"6","mb_lg":"","pt_md":"0","pr_md":"0","flex_order":"order-1","flex_order_lg":"order-lg-2","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md='12'  col_lg='6'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md='0'  pr_md='0'  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order='order-1'  flex_order_md=''  flex_order_lg='order-lg-2'  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-md-0 pe-md-0 col-md-12 col-lg-6 bg-image-fixed col order-1 order-lg-2"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Get Listed. Get Noticed. Grow Your Business.","html_tag":"h2","text_color":"white","text_color_custom":"#0c0d24","font_size":"display-4","font_weight":"font-weight-bold","text_align_lg":"text-lg-start"} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-white text-start font-weight-bold display-4">Get Listed. Get Noticed. Grow Your Business.</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Homeowners and businesses use our platform every day to find trustworthy builders and tradespeople — be one of them.","html_tag":"p","text_color":"white","font_size":"fs-5","text_align_lg":"text-lg-start","mt":"3","mb":"4","mr_md":"0","ml_md":"0","mt_lg":"3","mb_lg":"4"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mt-3 mb-4 me-md-0 ms-md-0 mt-lg-3 mb-lg-4 text-white text-start fs-5">Homeowners and businesses use our platform every day to find trustworthy builders and tradespeople — be one of them.</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-button {"text":"Get Listed Now","link_size":"large","font_size_custom":1.1,"font_weight":"font-weight-bold","font_case":"text-uppercase","mt_lg":"2","pt_lg":"3","pb_lg":"3","styleid":"block-4zcwjja02m","content":"\u003ca style=\u0022font-size:1.1rem;\u0022  class=\u0022btn btn-primary btn-lg mt-2 pt-3 pb-3 fw-bold text-uppercase block-4zcwjja02m\u0022\u003eGet Listed Now\u003c/a\u003e ","sd_shortcode":"[bs_button type='home'  page_id=''  meta_key=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Get Listed Now'  icon_class=''  icon_position=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type='btn'  link_size='large'  link_bg='primary'  link_bg_color='#0073aa'  link_bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color=''  text_color_custom=''  bg_hover=''  bg_hover_color='#0073aa'  bg_hover_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  text_color_hover=''  text_color_hover_custom=''  font_size_custom='1.1'  font_weight='font-weight-bold'  font_case='text-uppercase'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='2'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg=''  pb_lg='3'  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  display=''  display_md=''  display_lg=''  visibility_conditions=''  css_class=''  styleid='block-4zcwjja02m' ]"} /--></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->