<?php

/**
 * Title: BuildPros - Default Footer
 * Slug: buildpros/footer-default
 * Categories: blockstrap-site-footer
 * Viewport Width: 1280
 */

$img_url = esc_url(get_theme_file_uri('assets/images/logo-white.svg')); /* <?php echo esc_url( $img_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"secondary","bg_color":"rgba(229,229,229,0.62)","text_color":"white","mb_lg":"","pt":"5","pt_lg":"6","pb_lg":"3","position":"position-relative","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='secondary'  bg_color='rgba(229,229,229,0.62)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='5'  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='6'  pr_lg=''  pb_lg='3'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"block-1618467995"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-5 pt-lg-6 pb-3 bg-secondary bg-image-fixed text-white container-fluid position-relative"><!-- wp:blockstrap/blockstrap-widget-container {"bg":"custom-color","bg_color":"rgba(0,0,0,0.15)","mb_lg":"","pt":"0","pr":"4","pl":"4","pt_lg":"3","pr_lg":"5","pb_lg":"3","pl_lg":"5","border":"0","rounded":"rounded","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='custom-color'  bg_color='rgba(0,0,0,0.15)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='0'  pr='4'  pb=''  pl='4'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg='5'  pb_lg='3'  pl_lg='5'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"block-1618467995"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pe-4 ps-4 pt-lg-3 pe-lg-5 pb-3 ps-lg-5 border-0 bg-custom-color bg-image-fixed container rounded" style="background-color:rgba(0,0,0,0.15)"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","pt_lg":"5","position":"position-relative","sd_shortcode":"[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='5'  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"block-1618467995"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 pt-5 bg-image-fixed row position-relative"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"6","col_lg":"6","bg_on_text":true,"mt_lg":"n3","pt_lg":"3","pr_lg":"6","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md='6'  col_lg='6'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='true'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='n3'  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg='6'  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"block-1618467995"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mt-n3 mb-3 pt-3 pe-6 col-12 col-md-6 col-lg-6 bg-image-fixed col"><!-- wp:image {"id":5492,"width":"200px","sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full is-resized"><img src="<?php echo esc_url( $img_url ); ?>" alt="" class="wp-image-5492" style="width:200px"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph {"className":"mt-3","textColor":"white","fontSize":"small"} -->
<p class="mt-3 has-white-color has-text-color has-small-font-size">Connect homeowners and developers with trusted pros using BuildProDirect, a contractor and construction services directory featuring portfolios and client reviews.</p>
<!-- /wp:paragraph -->

<!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"0","flex_direction":"flex-column","ml_lg":"n3","pl_lg":"0","sd_shortcode":"[bs_nav anchor=''  inside_navbar='0'  container=''  flex_direction='flex-column'  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size=''  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='0'  mb_lg=''  ml_lg='n3'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]","sd_shortcode_close":"[/bs_nav]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav" id="navbarNav_"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto me-lg-0 ms-lg-n3 ps-0 flex-column"><!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"info@ayecode.io","icon_class":"far fa-envelope","link_bg":"white","text_color":"white","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#https://buildpros.local\u0022 class=\u0022nav-link link-white fw-normal\u0022 \u003e\u003ci class=\u0022far fa-envelope me-2\u0022\u003e\u003c/i\u003einfo@ayecode.io\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='info@ayecode.io'  icon_class='far fa-envelope'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"+123 456 789","icon_class":"fa-solid fa-mobile-screen","link_bg":"white","text_color":"white","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#https://buildpros.local\u0022 class=\u0022nav-link link-white fw-normal\u0022 \u003e\u003ci class=\u0022fa-solid fa-mobile-screen me-2\u0022\u003e\u003c/i\u003e+123 456 789\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='+123 456 789'  icon_class='fa-solid fa-mobile-screen'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /--></ul></div>
<!-- /wp:blockstrap/blockstrap-widget-nav -->

<!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"0","ml_lg":"n3","sd_shortcode":"[bs_nav anchor=''  inside_navbar='0'  container=''  flex_direction=''  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size=''  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg='0'  mb_lg=''  ml_lg='n3'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]","sd_shortcode_close":"[/bs_nav]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav" id="navbarNav_"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto me-lg-0 ms-lg-n3"><!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#facebook","icon_class":"fab fa-facebook","link_bg":"white","text_color":"white","content":"\u003ca href=\u0022##facebook\u0022 class=\u0022nav-link link-white \u0022 \u003e\u003ci class=\u0022fab fa-facebook\u0022\u003e\u003c/i\u003e\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='custom'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url='#facebook'  text=''  icon_class='fab fa-facebook'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#twriiter","icon_class":"fab fa-twitter","link_bg":"white","text_color":"white","content":"\u003ca href=\u0022##twriiter\u0022 class=\u0022nav-link link-white \u0022 \u003e\u003ci class=\u0022fab fa-twitter\u0022\u003e\u003c/i\u003e\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='custom'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url='#twriiter'  text=''  icon_class='fab fa-twitter'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"custom","custom_url":"#instagram","icon_class":"fab fa-instagram","link_bg":"white","text_color":"white","content":"\u003ca href=\u0022##instagram\u0022 class=\u0022nav-link link-white \u0022 \u003e\u003ci class=\u0022fab fa-instagram\u0022\u003e\u003c/i\u003e\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='custom'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url='#instagram'  text=''  icon_class='fab fa-instagram'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='white'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /--></ul></div>
<!-- /wp:blockstrap/blockstrap-widget-nav --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"6","col_lg":"3","text_color":"dark","content":"","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md='6'  col_lg='3'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color='dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"block-1618467995"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 col-12 col-md-6 col-lg-3 bg-image-fixed text-dark col"><!-- wp:heading {"style":{"typography":{"fontSize":"1.3rem","fontStyle":"normal","fontWeight":"700"},"elements":{"link":{"color":{"text":"var:preset|color|white"}}}},"textColor":"white"} -->
<h2 class="wp-block-heading has-white-color has-text-color has-link-color" style="font-size:1.3rem;font-style:normal;font-weight:700">Get Involved</h2>
<!-- /wp:heading -->

<!-- wp:blockstrap/blockstrap-widget-nav {"inside_navbar":"0","flex_direction":"flex-column","mr_lg":"","ml_lg":"n3","sd_shortcode":"[bs_nav anchor=''  inside_navbar='0'  container=''  flex_direction='flex-column'  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size=''  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='n3'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]","sd_shortcode_close":"[/bs_nav]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav" id="navbarNav_"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto ms-lg-n3 flex-column"><!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Home","link_bg":"gray","text_color":"white","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#https://buildpros.local\u0022 class=\u0022nav-link link-white fw-normal\u0022 \u003eHome\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Home'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"About us","link_bg":"gray","text_color":"white","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#https://buildpros.local\u0022 class=\u0022nav-link link-white fw-normal\u0022 \u003eAbout us\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='About us'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg='gray'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Contact us","text_color":"white","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#https://buildpros.local\u0022 class=\u0022nav-link link-white fw-normal\u0022 \u003eContact us\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Contact us'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Team","text_color":"white","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#https://buildpros.local\u0022 class=\u0022nav-link link-white fw-normal\u0022 \u003eTeam\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Team'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /--></ul></div>
<!-- /wp:blockstrap/blockstrap-widget-nav --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_md":"6","col_lg":"3","text_color":"dark","content":"","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md='6'  col_lg='3'  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color='dark'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='3'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"block-1618467995"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-3 col-12 col-md-6 col-lg-3 bg-image-fixed text-dark col"><!-- wp:heading {"style":{"typography":{"fontSize":"1.3rem","fontStyle":"normal","fontWeight":"700"},"elements":{"link":{"color":{"text":"var:preset|color|white"}}}},"textColor":"white"} -->
<h2 class="wp-block-heading has-white-color has-text-color has-link-color" style="font-size:1.3rem;font-style:normal;font-weight:700">Useful links</h2>
<!-- /wp:heading -->

<!-- wp:blockstrap/blockstrap-widget-nav {"anchor":"footer-nav-1","inside_navbar":"0","flex_direction":"flex-column","mr_lg":"","ml_lg":"n3","pl_lg":"0","sd_shortcode":"[bs_nav anchor='footer-nav-1'  inside_navbar='0'  container=''  flex_direction='flex-column'  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size=''  font_size_custom=''  bg=''  mt=''  mr='auto'  mb=''  ml='auto'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='n3'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  width=''  css_class='' ]","sd_shortcode_close":"[/bs_nav]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav" id="navbarNav_footer-nav-1"><ul class="wp-block-blockstrap-blockstrap-widget-nav nav me-auto ms-auto ms-lg-n3 ps-0 flex-column"><!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Terms of use","text_color":"white","font_weight":"font-weight-normal","ml_lg":"0","pl_lg":"0","content":"\u003ca href=\u0022#https://buildpros.local\u0022 class=\u0022nav-link link-white fw-normal\u0022 \u003eTerms of use\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Terms of use'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='0'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Legal notice","text_color":"white","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#https://buildpros.local\u0022 class=\u0022nav-link link-white fw-normal\u0022 \u003eLegal notice\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Legal notice'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Privacy policy","text_color":"white","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#https://buildpros.local\u0022 class=\u0022nav-link link-white fw-normal\u0022 \u003ePrivacy policy\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Privacy policy'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"text":"Add Listing","text_color":"white","font_weight":"font-weight-normal","content":"\u003ca href=\u0022#https://buildpros.local\u0022 class=\u0022nav-link link-white fw-normal\u0022 \u003eAdd Listing\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='home'  page_id=''  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Add Listing'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg=''  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-normal'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /--></ul></div>
<!-- /wp:blockstrap/blockstrap-widget-nav --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"row","mt_lg":"4","mb_lg":"","sd_shortcode":"[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='4'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]","className":"border-top border-gray-dark"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mt-4 bg-image-fixed row"><!-- wp:paragraph {"align":"center","style":{"typography":{"fontSize":"0.8rem"}},"textColor":"gray"} -->
<p class="has-text-align-center has-gray-color has-text-color" style="font-size:0.8rem">Copyright © BlockStrap 2022. All rights reserved.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->