<?php

/**
 * Title: buildpros - Default Header
 * Slug: buildpros/header-default
 * Categories: blockstrap-site-header
 * Viewport Width: 1280
 */

$img_url = esc_url(get_theme_file_uri('assets/images/logo-white.svg')); /* <?php echo esc_url( $img_url ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-skip-links {"content":"\u003ca href=\u0022#main\u0022 class=\u0022btn btn-primary\u0022\u003eSkip to main content\u003c/a\u003e","sd_shortcode":"[bs_skip_links text1='Skip to main content'  hash1='main'  text2=''  hash2=''  text3=''  hash3=''  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size=''  shadow=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-navbar {"bg":"primary","bg_color":"rgba(255,255,255,0.84)","bgtus":true,"cscos":true,"container":"navbar-dark","inner_container":"container","mb_lg":"","border":"0","position":"fixed-top","content":"\u003ca href=\u0022#https://buildpros.local/place/\u0022 class=\u0022nav-link pe-4 ps-4 fw-normal\u0022 \u003eFind Charities\u003cspan class=\u0022navbar-divider d-none d-lg-block position-absolute top-50 end-0 translate-middle-y\u0022\u003e\u003c/span\u003e\u003c/a\u003e","sd_shortcode":"[bs_navbar bg='primary'  bg_color='rgba(255,255,255,0.84)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bgtus='true'  cscos='true'  container='navbar-dark'  inner_container='container'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  rounded=''  rounded_size=''  shadow=''  position='fixed-top'  sticky_offset_top=''  sticky_offset_bottom='' ]","sd_shortcode_close":"[/bs_navbar]"} -->
<nav class="navbar navbar-expand-lg border-0 bg-primary bg-image-fixed bg-transparent-until-scroll color-scheme-flip-on-scroll navbar-dark fixed-top"><div class="wp-block-blockstrap-blockstrap-widget-navbar container"><!-- wp:blockstrap/blockstrap-widget-navbar-brand {"text":"","icon_image":"<?php echo esc_url( $img_url ); ?>","img_max_width":170,"custom_url":"/","brand_font_size":"0","brand_font_weight":"font-weight-normal","bg_gradient":"linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)","bg_on_text":true,"mb_lg":"","pl":"3","pl_lg":"0","rounded_size":"lg","sd_shortcode":"[bs_navbar_brand text=''  icon_image='<?php echo esc_url( $img_url ); ?>'  img_max_width='170'  type='home'  custom_url='/'  text_color=''  brand_font_size='0'  brand_font_weight='font-weight-normal'  brand_font_italic=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgb(34,227,7) 0%,rgb(245,245,245) 100%)'  bg_on_text='true'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl='3'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  rounded=''  rounded_size='lg'  shadow=''  css_class='' ]"} -->
<a class="navbar-brand d-flex align-items-center ps-3 ps-lg-0 rounded-lg" href="https://buildpros.local"><img class="" alt="Site logo" src="<?php echo esc_url( $img_url ); ?>" style="max-width:170px" width="170" height="50"/><span class="mb-0 props.attributes.brand_font_size props.attributes.brand_font_weight props.attributes.brand_font_italic"></span></a>
<!-- /wp:blockstrap/blockstrap-widget-navbar-brand -->

<!-- wp:blockstrap/blockstrap-widget-nav {"anchor":"main-nav","font_size":"fs-5","mr":"","ml":"","mr_lg":"","ml_lg":"","rounded_size":"lg","width":"w-100","sd_shortcode":"[bs_nav anchor='main-nav'  inside_navbar='1'  container=''  flex_direction=''  nav_style=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  nav_fill=''  font_size='fs-5'  font_size_custom=''  bg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  rounded=''  rounded_size='lg'  shadow=''  width='w-100'  css_class='' ]","sd_shortcode_close":"[/bs_nav]"} -->
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav_main-nav" aria-label="Open menu"><span class="navbar-toggler-icon"></span></button><div class="wp-block-blockstrap-blockstrap-widget-nav blockstrap-nav collapse navbar-collapse" id="navbarNav_main-nav"><ul class="wp-block-blockstrap-blockstrap-widget-nav navbar-nav rounded-lg w-100 fs-5"><!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"gd_place","page_id":"6674","text":"Browse Contractors","link_pr_lg":"4","link_pl_lg":"4","text_color":"white","font_weight":"font-weight-bold","ml":"0","border":"0","content":"\u003ca href=\u0022#https://buildpros.local/place/\u0022 class=\u0022nav-link link-white pe-4 ps-4 fw-bold\u0022 \u003eBrowse Contractors\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='gd_place'  page_id='6674'  post_id=''  taxonomy=''  term_id=''  custom_url=''  text='Browse Contractors'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg='4'  link_pb_lg=''  link_pl_lg='4'  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml='0'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"3336","custom_url":"/blog","text":"Blog","link_pr_lg":"4","link_pl_lg":"4","text_color":"white","font_weight":"font-weight-bold","border":"0","content":"\u003ca href=\u0022#https://buildpros.local/blog/\u0022 class=\u0022nav-link link-white pe-4 ps-4 fw-bold\u0022 \u003eBlog\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='3336'  post_id=''  taxonomy=''  term_id=''  custom_url='/blog'  text='Blog'  icon_class=''  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size=''  link_bg=''  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg='4'  link_pb_lg=''  link_pl_lg='4'  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /-->

<!-- wp:blockstrap/blockstrap-widget-nav-item {"type":"page","page_id":"4426","custom_url":"#about","text":"Get Listed","icon_class":"fas fa-plus-circle","link_size":"large","link_bg":"primary","link_pr_lg":"0","text_color":"white","font_weight":"font-weight-bold","ml":"0","ml_lg":"auto","border":"0","content":"\u003ca href=\u0022#https://buildpros.local/add-listing/\u0022 class=\u0022nav-link link-white pe-0 fw-bold\u0022 \u003e\u003ci class=\u0022fas fa-plus-circle me-2\u0022\u003e\u003c/i\u003eGet Listed\u003c/a\u003e","sd_shortcode":"[bs_nav_item type='page'  page_id='4426'  post_id=''  taxonomy=''  term_id=''  custom_url='#about'  text='Get Listed'  icon_class='fas fa-plus-circle'  icon_aria_label=''  link_new_window='false'  link_nofollow='false'  link_attributes=''  link_type=''  link_size='large'  link_bg='primary'  link_pt=''  link_pr=''  link_pb=''  link_pl=''  link_pt_md=''  link_pr_md=''  link_pb_md=''  link_pl_md=''  link_pt_lg=''  link_pr_lg='0'  link_pb_lg=''  link_pl_lg=''  link_divider=''  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  font_weight='font-weight-bold'  mt=''  mr=''  mb=''  ml='0'  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg='auto'  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  rounded=''  rounded_size=''  shadow=''  visibility_conditions=''  css_class='' ]"} /--></ul></div>
<!-- /wp:blockstrap/blockstrap-widget-nav --></div></nav>
<!-- /wp:blockstrap/blockstrap-widget-navbar -->