<?php
/**
 * Title: BuildPros - Testimonials
 * Slug: buildpros/testimonials
 * Categories: blockstrap-page-content
 * Viewport Width: 1280
 */

$img_url_1 = esc_url( get_theme_file_uri( 'assets/images/demo/testimonial-5.jpg' ) ); /* <?php echo esc_url( $img_url_1 ); ?> */
$img_url_2 = esc_url( get_theme_file_uri( 'assets/images/demo/testimonial-3.jpg' ) ); /* <?php echo esc_url( $img_url_2 ); ?> */
$img_url_3 = esc_url( get_theme_file_uri( 'assets/images/demo/testimonial-1.jpg' ) ); /* <?php echo esc_url( $img_url_3 ); ?> */

?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg":"white","bg_color":"rgba(0,0,0,0.53)","bg_gradient":"radial-gradient(rgb(5,63,40) 0%,rgba(11,23,18,0.93) 100%)","bg_image_xy":{"x":0.74,"y":0.38},"text_color":"white","mb_lg":"","pt":"0","pb":"0","pt_lg":"6","pb_lg":"7","position":"position-relative","content":"\u003cdiv class=\u0022bs-counter-number-wrapper text-dark text-start fw-bold  h1 \u0022  \u003e\u003cspan class=\u0022bs-counter-number\u0022 data-auicounter data-auistart=\u00220\u0022 data-auiend=\u002256\u0022 data-auiduration=\u00222000\u0022 data-auisep=\u0022\u0022\u003e56\u003c/span\u003e\u003cspan class=\u0022bs-counter-suffix\u0022\u003eK+\u003c/span\u003e\u003c/div\u003e\u003cdiv class=\u0022bs-counter-title text-start fs-5 \u0022 \u003eMonthly Users\u003c/div\u003e","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='white'  bg_color='rgba(0,0,0,0.53)'  bg_gradient='radial-gradient(rgb(5,63,40) 0%,rgba(11,23,18,0.93) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='0'  pr=''  pb='0'  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='6'  pr_lg=''  pb_lg='7'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pb-0 pt-lg-6 pb-lg-7 bg-white bg-image-fixed text-white container-fluid position-relative"><!-- wp:blockstrap/blockstrap-widget-container {"container":"container-xxl","mb_lg":"","sd_shortcode":"[bs_container container='container-xxl'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container bg-image-fixed container-xxl"><!-- wp:blockstrap/blockstrap-widget-container {"mb_lg":"","pr":"0","pl":"0","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='0'  pb=''  pl='0'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pe-0 ps-0 bg-image-fixed container"><!-- wp:blockstrap/blockstrap-widget-container {"container":"row","row_cols_lg":"1","text_align_lg":"text-lg-start","mb_lg":"","position":"position-relative","flex_align_items_lg":"align-items-lg-center","sd_shortcode":"[bs_container container='row'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg='1'  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-start'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container row-cols-1 bg-image-fixed text-start row position-relative align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"6","bg_color":"rgba(255,255,255,0.06)","mb_lg":"","pt":"4","pr":"3","pb":"4","pl":"3","pr_lg":"5","border":"danger","display_lg":"d-lg-flex","flex_align_items_lg":"align-items-lg-center","flex_justify_content_lg":"justify-content-lg-center","css_class":"h-100","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='6'  bg=''  bg_color='rgba(255,255,255,0.06)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='4'  pr='3'  pb='4'  pl='3'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg='5'  pb_lg=''  pl_lg=''  border='danger'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-center'  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='h-100' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-4 pe-3 pb-4 ps-3 pe-lg-5 col-12 col-lg-6  border-danger bg-image-fixed d-flex col h-100 align-items-center justify-content-center"><!-- wp:blockstrap/blockstrap-widget-container {"mb_lg":"","pr":"0","pl":"0","rounded":"rounded","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='0'  pb=''  pl='0'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pe-0 ps-0 bg-image-fixed container rounded"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"Real people. Real results.","html_tag":"h1","text_color":"primary","text_color_custom":"#0c0d24","font_size":"fs-4","text_align_lg":"text-lg-start","mb_lg":""} -->
<h1 class="wp-block-blockstrap-blockstrap-widget-heading text-primary text-start fs-4">Real people. Real results.</h1>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"See why users trust our directory","html_tag":"h1","text_color":"dark","text_color_custom":"#0c0d24","font_size":"display-1","font_weight":"font-weight-bold","text_align_lg":"text-lg-start","mb_lg":""} -->
<h1 class="wp-block-blockstrap-blockstrap-widget-heading text-dark text-start font-weight-bold display-1">See why users trust our directory</h1>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"6","bg":"secondary","bg_color":"rgba(255,255,255,0.06)","text_align_lg":"text-lg-start","mb":"4","mb_lg":"0","pt":"5","pr":"4","pb":"5","pl":"4","pt_lg":"6","pr_lg":"6","pb_lg":"6","pl_lg":"6","border":"secondary","rounded":"rounded","display_lg":"d-lg-flex","flex_align_items_lg":"align-items-lg-center","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='6'  bg='secondary'  bg_color='rgba(255,255,255,0.06)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-start'  mt=''  mr=''  mb='4'  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='0'  ml_lg=''  pt='5'  pr='4'  pb='5'  pl='4'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='6'  pr_lg='6'  pb_lg='6'  pl_lg='6'  border='secondary'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg='align-items-lg-center'  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mb-4 mb-lg-0 pt-5 pe-4 pb-5 ps-4 pt-lg-6 pe-lg-6 pb-lg-6 ps-lg-6 col-12 col-lg-6  border-secondary bg-secondary bg-image-fixed text-start d-flex col rounded align-items-center"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card","h100":"h-100","bg":"transparent","mb_lg":"","border":"0","rounded_size":"0","sd_shortcode":"[bs_container container='card'  h100='h-100'  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='transparent'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size='0'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container border-0 rounded-0 bg-transparent bg-image-fixed card h-100"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card-img-top","mb_lg":"","border":"0","rounded":"rounded","display_lg":"d-lg-flex","flex_justify_content_lg":"justify-content-lg-center","overflow":"overflow-hidden","sd_shortcode":"[bs_container container='card-img-top'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-center'  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow='overflow-hidden'  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container border-0 bg-image-fixed d-flex card-img-top rounded justify-content-center overflow-hidden"><!-- wp:image {"id":5502,"width":"150px","height":"150px","scale":"cover","sizeSlug":"medium","linkDestination":"none","align":"center","className":"is-style-rounded"} -->
<figure class="wp-block-image aligncenter size-medium is-resized is-style-rounded"><img src="<?php echo esc_url( $img_url_1 ); ?>" alt="" class="wp-image-5502" style="object-fit:cover;width:150px;height:150px"/></figure>
<!-- /wp:image --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"card-body","text_align_lg":"text-lg-center","mb_lg":"","pt_lg":"0","pr_lg":"0","pb_lg":"0","pl_lg":"0","rounded":"rounded","sd_shortcode":"[bs_container container='card-body'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='0'  pb_lg='0'  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pe-0 pb-0 ps-0 bg-image-fixed text-center card-body rounded"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"\u0022 \u003cem\u003eI found a top-rated general contractor through this site, and my renovation went smoothly from start to finish.\u003c/em\u003e \u0022","html_tag":"p","text_color":"white","font_size":"fs-4","font_line_height":1.6,"font_weight":"font-italic"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-white font-italic fs-4" style="line-height:1.6">" <em>I found a top-rated general contractor through this site, and my renovation went smoothly from start to finish.</em> "</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"James L.","html_tag":"h6","text_color":"primary","font_size":"fs-5","font_weight":"font-weight-bold","mb_lg":"0"} -->
<h6 class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-primary font-weight-bold fs-5">James L.</h6>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Small Business Owner","html_tag":"div","text_color":"gray-dark","text_color_custom":"#949494","font_size":"fs-6","mb_lg":""} -->
<div class="wp-block-blockstrap-blockstrap-widget-heading text-gray-dark fs-6">Small Business Owner</div>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"6","bg":"primary","bg_color":"rgba(255,255,255,0.06)","mb_lg":"","pt":"5","pr":"4","pb":"5","pl":"4","pt_lg":"6","pr_lg":"6","pb_lg":"6","pl_lg":"6","border":"primary","rounded":"rounded","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='6'  bg='primary'  bg_color='rgba(255,255,255,0.06)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='5'  pr='4'  pb='5'  pl='4'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='6'  pr_lg='6'  pb_lg='6'  pl_lg='6'  border='primary'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-5 pe-4 pb-5 ps-4 pt-lg-6 pe-lg-6 pb-lg-6 ps-lg-6 col-12 col-lg-6  border-primary bg-primary bg-image-fixed col rounded"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card","h100":"h-100","bg":"transparent","mb_lg":"","border":"0","rounded_size":"0","sd_shortcode":"[bs_container container='card'  h100='h-100'  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='transparent'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size='0'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container border-0 rounded-0 bg-transparent bg-image-fixed card h-100"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card-img-top","mb_lg":"","border":"0","rounded":"rounded","display_lg":"d-lg-flex","flex_justify_content_lg":"justify-content-lg-center","overflow":"overflow-hidden","sd_shortcode":"[bs_container container='card-img-top'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-center'  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow='overflow-hidden'  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container border-0 bg-image-fixed d-flex card-img-top rounded justify-content-center overflow-hidden"><!-- wp:image {"id":5500,"width":"150px","height":"150px","scale":"cover","sizeSlug":"medium","linkDestination":"none","align":"center","className":"is-style-rounded"} -->
<figure class="wp-block-image aligncenter size-medium is-resized is-style-rounded"><img src="<?php echo esc_url( $img_url_2 ); ?>" alt="" class="wp-image-5500" style="object-fit:cover;width:150px;height:150px"/></figure>
<!-- /wp:image --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"card-body","text_align_lg":"text-lg-center","mb_lg":"","pt_lg":"0","pr_lg":"0","pb_lg":"0","pl_lg":"0","rounded":"rounded","sd_shortcode":"[bs_container container='card-body'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='0'  pb_lg='0'  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pe-0 pb-0 ps-0 bg-image-fixed text-center card-body rounded"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"\u0022 \u003cem\u003eNeeded a commercial builder fast — the directory made it easy to compare pros and choose the right one for the job.\u003c/em\u003e \u0022","html_tag":"p","text_color":"white","font_size":"fs-4","font_line_height":1.6,"font_weight":"font-italic"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-white font-italic fs-4" style="line-height:1.6">" <em>Needed a commercial builder fast — the directory made it easy to compare pros and choose the right one for the job.</em> "</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Daniel T.","html_tag":"h6","text_color":"white","font_size":"fs-5","font_weight":"font-weight-bold","mb_lg":"0"} -->
<h6 class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-white font-weight-bold fs-5">Daniel T.</h6>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Industrial Project Lead","html_tag":"div","text_color":"white","text_color_custom":"#949494","font_size":"fs-6","mb_lg":""} -->
<div class="wp-block-blockstrap-blockstrap-widget-heading text-white fs-6">Industrial Project Lead</div>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"col","col":"12","col_lg":"6","bg_color":"rgba(255,255,255,0.06)","mb_lg":"","pt":"5","pr":"4","pb":"5","pl":"4","pt_lg":"6","pr_lg":"6","pb_lg":"6","pl_lg":"6","border":"0","rounded":"rounded","sd_shortcode":"[bs_container container='col'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col='12'  col_md=''  col_lg='6'  bg=''  bg_color='rgba(255,255,255,0.06)'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='5'  pr='4'  pb='5'  pl='4'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='6'  pr_lg='6'  pb_lg='6'  pl_lg='6'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-5 pe-4 pb-5 ps-4 pt-lg-6 pe-lg-6 pb-lg-6 ps-lg-6 col-12 col-lg-6 border-0 bg-image-fixed col rounded"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card","h100":"h-100","bg":"transparent","mb_lg":"","border":"0","rounded_size":"0","sd_shortcode":"[bs_container container='card'  h100='h-100'  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='transparent'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size='0'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container border-0 rounded-0 bg-transparent bg-image-fixed card h-100"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card-img-top","mb_lg":"","border":"0","rounded":"rounded","display_lg":"d-lg-flex","flex_justify_content_lg":"justify-content-lg-center","overflow":"overflow-hidden","sd_shortcode":"[bs_container container='card-img-top'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg='d-lg-flex'  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg='justify-content-lg-center'  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow='overflow-hidden'  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container border-0 bg-image-fixed d-flex card-img-top rounded justify-content-center overflow-hidden"><!-- wp:image {"id":5498,"width":"150px","height":"150px","scale":"cover","sizeSlug":"medium","linkDestination":"none","align":"center","className":"is-style-rounded"} -->
<figure class="wp-block-image aligncenter size-medium is-resized is-style-rounded"><img src="<?php echo esc_url( $img_url_3 ); ?>" alt="" class="wp-image-5498" style="object-fit:cover;width:150px;height:150px"/></figure>
<!-- /wp:image --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"card-body","text_align_lg":"text-lg-center","mb_lg":"","pt_lg":"0","pr_lg":"0","pb_lg":"0","pl_lg":"0","rounded":"rounded","sd_shortcode":"[bs_container container='card-body'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg='text-lg-center'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='0'  pb_lg='0'  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-0 pe-0 pb-0 ps-0 bg-image-fixed text-center card-body rounded"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"\u0022 \u003cem\u003eFrom plumbing to roofing, I’ve hired multiple contractors using this platform and have yet to be disappointed.\u003c/em\u003e \u0022","html_tag":"p","text_color":"dark","font_size":"fs-4","font_line_height":1.6,"font_weight":"font-italic"} -->
<p class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-dark font-italic fs-4" style="line-height:1.6">" <em>From plumbing to roofing, I’ve hired multiple contractors using this platform and have yet to be disappointed.</em> "</p>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Jhon M.","html_tag":"h6","text_color":"primary","font_size":"fs-5","font_weight":"font-weight-bold","mb_lg":"0"} -->
<h6 class="wp-block-blockstrap-blockstrap-widget-heading mb-0 text-primary font-weight-bold fs-5">Jhon M.</h6>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:blockstrap/blockstrap-widget-heading {"text":"Homeowner in Austin","html_tag":"div","text_color":"gray-dark","text_color_custom":"#949494","font_size":"fs-6","mb_lg":""} -->
<div class="wp-block-blockstrap-blockstrap-widget-heading text-gray-dark fs-6">Homeowner in Austin</div>
<!-- /wp:blockstrap/blockstrap-widget-heading --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->