<?php

/**
 * Title: BuildPros: 3-column cards (What’s New in the Building World)
 * Slug: buildpros/three-col-posts
 * Categories: blockstrap-page-content
 * Viewport Width: 1280
 */
?>

<!-- wp:blockstrap/blockstrap-widget-container {"container":"container-fluid","bg_color":"rgba(0,0,0,0.85)","bg_gradient":"radial-gradient(rgb(5,63,40) 0%,rgba(11,23,18,0.93) 100%)","bg_image_fixed":true,"bg_image_xy":{"x":0.75,"y":0.99},"text_color":"white","mb_lg":"","pt":"5","pb":"0","pt_lg":"7","pb_lg":"5","position":"position-relative","content":"\u003cdiv class=\u0022bs-counter-number-wrapper text-dark text-start fw-bold  h1 \u0022  \u003e\u003cspan class=\u0022bs-counter-number\u0022 data-auicounter data-auistart=\u00220\u0022 data-auiend=\u002256\u0022 data-auiduration=\u00222000\u0022 data-auisep=\u0022\u0022\u003e56\u003c/span\u003e\u003cspan class=\u0022bs-counter-suffix\u0022\u003eK+\u003c/span\u003e\u003c/div\u003e\u003cdiv class=\u0022bs-counter-title text-start fs-5 \u0022 \u003eMonthly Users\u003c/div\u003e","sd_shortcode":"[bs_container container='container-fluid'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='rgba(0,0,0,0.85)'  bg_gradient='radial-gradient(rgb(5,63,40) 0%,rgba(11,23,18,0.93) 100%)'  bg_image_fixed='true'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt='5'  pr=''  pb='0'  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='7'  pr_lg=''  pb_lg='5'  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-5 pb-0 pt-lg-7 pb-lg-5 bg-image-fixed text-white container-fluid position-relative"><!-- wp:blockstrap/blockstrap-widget-container {"bg_color":"rgba(0,0,0,0.85)","bg_gradient":"radial-gradient(rgb(5,63,40) 0%,rgba(11,23,18,0.93) 100%)","bg_image_fixed":true,"bg_image_xy":{"x":0.75,"y":0.99},"text_color":"white","mb_lg":"","pr":"0","pl":"0","position":"position-relative","content":"\u003cdiv class=\u0022bs-counter-number-wrapper text-dark text-start fw-bold  h1 \u0022  \u003e\u003cspan class=\u0022bs-counter-number\u0022 data-auicounter data-auistart=\u00220\u0022 data-auiend=\u002256\u0022 data-auiduration=\u00222000\u0022 data-auisep=\u0022\u0022\u003e56\u003c/span\u003e\u003cspan class=\u0022bs-counter-suffix\u0022\u003eK+\u003c/span\u003e\u003c/div\u003e\u003cdiv class=\u0022bs-counter-title text-start fs-5 \u0022 \u003eMonthly Users\u003c/div\u003e","sd_shortcode":"[bs_container container='container'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='rgba(0,0,0,0.85)'  bg_gradient='radial-gradient(rgb(5,63,40) 0%,rgba(11,23,18,0.93) 100%)'  bg_image_fixed='true'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color='white'  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr='0'  pb=''  pl='0'  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border=''  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size=''  shadow=''  position='position-relative'  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pe-0 ps-0 bg-image-fixed text-white container position-relative"><!-- wp:blockstrap/blockstrap-widget-heading {"text":"What’s New in the Building World","html_tag":"h2","text_color_custom":"#0c0d24","font_size":"display-5","font_weight":"font-weight-bold","text_align_lg":"text-lg-start"} -->
<h2 class="wp-block-blockstrap-blockstrap-widget-heading mb-3 text-start font-weight-bold display-5">What’s New in the Building World</h2>
<!-- /wp:blockstrap/blockstrap-widget-heading -->

<!-- wp:query {"queryId":1,"query":{"pages":"","offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","sticky":"","exclude":[],"perPage":3,"inherit":false},"layout":{"type":"default"}} -->
<div class="wp-block-query"><!-- wp:post-template {"layout":{"type":"grid","columnCount":3}} -->
<!-- wp:blockstrap/blockstrap-widget-container {"container":"card","h100":"h-100","bg":"white","mt_lg":"3","mb_lg":"","pt_lg":"0","pr_lg":"0","pb_lg":"0","pl_lg":"0","border":"0","rounded":"rounded","rounded_size":"lg","overflow":"overflow-hidden","sd_shortcode":"[bs_container container='card'  h100='h-100'  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='white'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg='3'  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='0'  pr_lg='0'  pb_lg='0'  pl_lg='0'  border='0'  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size='lg'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow='overflow-hidden'  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container mt-3 pt-0 pe-0 pb-0 ps-0 border-0 rounded-lg bg-white bg-image-fixed card rounded h-100 overflow-hidden"><!-- wp:blockstrap/blockstrap-widget-container {"container":"card-img-top","bg":"white","mb_lg":"","border":"0","border_type":"border","rounded_size":"0","overflow":"overflow-hidden","sd_shortcode":"[bs_container container='card-img-top'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg='white'  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  border_type='border'  border_width=''  border_opacity=''  rounded=''  rounded_size='0'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow='overflow-hidden'  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container border-0 rounded-0 bg-white bg-image-fixed card-img-top border overflow-hidden"><!-- wp:blockstrap/blockstrap-widget-image {"img_src":"featured","fallback_img_src":"default","img_link_to":"post","img_aspect":"16by9","img_border":"0","img_rounded_size":"0","mb_lg":"0","border":"0","rounded_size":"0","content":"\u003cfigure class=\u0022overflow-hidden mb-0 border-0 rounded-0 \u0022 style=\u0022 \u0022\u003e\u003ca href=\u0022#\u0022 class=\u0022 ratio ratio-16x9  embed-has-action position-relative\u0022 \u003e\u003cimg src=\u0022https://buildpros.local/wp-content/plugins/blockstrap-page-builder-blocks//assets/images/block-image-placeholder.jpg\u0022 class=\u0022mw-100 w-100 embed-item-cover-xy  \u0022 /\u003e\u003ci class=\u0022fas fa-link w-auto h-auto\u0022\u003e\u003c/i\u003e\u003c/a\u003e\u003c/figure\u003e","sd_shortcode":"[bs_image img_src='featured'  img_image=''  img_image_id=''  img_size=''  img_url=''  fallback_img_src='default'  fallback_img_image=''  fallback_img_image_id=''  img_alt=''  img_lazyload=''  img_link_to='post'  img_link=''  img_link_lightbox=''  lightbox_size='full'  img_link_hover_effect=''  text=''  col=''  col_md=''  col_lg=''  img_aspect='16by9'  img_cover=''  img_border='0'  img_border_width=''  img_border_opacity=''  img_rounded=''  img_rounded_size='0'  img_shadow=''  img_overlay=''  text_color=''  font_size=''  font_size_custom=''  font_weight=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  bg_on_text='false'  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg='0'  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg=''  pr_lg=''  pb_lg=''  pl_lg=''  border='0'  border_type=''  border_width=''  border_opacity=''  rounded=''  rounded_size='0'  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  float=''  float_md=''  float_lg=''  img_mask=''  img_mask_position='center center'  visibility_conditions=''  css_class='' ]"} /--></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->

<!-- wp:blockstrap/blockstrap-widget-container {"container":"card-body","mb_lg":"","pt_lg":"3","pl_lg":"0","rounded":"rounded","sd_shortcode":"[bs_container container='card-body'  h100=''  row_cols=''  row_cols_md=''  row_cols_lg=''  col=''  col_md=''  col_lg=''  bg=''  bg_color='#0073aa'  bg_gradient='linear-gradient(135deg,rgba(6,147,227,1) 0%,rgb(155,81,224) 100%)'  bg_image_fixed='false'  bg_image_use_featured='false'  bg_image=''  bg_image_id=''  bg_on_text='false'  text_color=''  text_justify='false'  text_align=''  text_align_md=''  text_align_lg=''  mt=''  mr=''  mb=''  ml=''  mt_md=''  mr_md=''  mb_md=''  ml_md=''  mt_lg=''  mr_lg=''  mb_lg=''  ml_lg=''  pt=''  pr=''  pb=''  pl=''  pt_md=''  pr_md=''  pb_md=''  pl_md=''  pt_lg='3'  pr_lg=''  pb_lg=''  pl_lg='0'  border=''  border_type=''  border_width=''  border_opacity=''  rounded='rounded'  rounded_size=''  shadow=''  position=''  sticky_offset_top=''  sticky_offset_bottom=''  display=''  display_md=''  display_lg=''  flex_align_items=''  flex_align_items_md=''  flex_align_items_lg=''  flex_justify_content=''  flex_justify_content_md=''  flex_justify_content_lg=''  flex_align_self=''  flex_align_self_md=''  flex_align_self_lg=''  flex_order=''  flex_order_md=''  flex_order_lg=''  overflow=''  max_height=''  scrollbars=''  hover_animations=''  visibility_conditions=''  anchor=''  css_class='' ]","sd_shortcode_close":"[/bs_container]"} -->
<div class="wp-block-blockstrap-blockstrap-widget-container pt-3 ps-0 bg-image-fixed card-body rounded"><!-- wp:post-date {"style":{"typography":{"fontSize":"0.9rem","fontStyle":"normal","fontWeight":"600"},"elements":{"link":{"color":{"text":"var:preset|color|primary"}}}},"textColor":"primary"} /-->

<!-- wp:spacer {"height":"7px"} -->
<div style="height:7px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:post-title {"isLink":true,"style":{"elements":{"link":{"color":{"text":"var:preset|color|dark"}}},"typography":{"fontStyle":"normal","fontWeight":"700"}},"textColor":"dark","fontSize":"large"} /--></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->
<!-- /wp:post-template --></div>
<!-- /wp:query --></div>
<!-- /wp:blockstrap/blockstrap-widget-container --></div>
<!-- /wp:blockstrap/blockstrap-widget-container -->